name: in_the_hood
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.0.0
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.6.12
  firebase_storage: ^12.0.0
  firebase_messaging: ^15.0.0
  google_maps_flutter: ^2.14.0
  google_mobile_ads: ^6.0.0
  provider: ^6.1.5+1
  geolocator: ^10.0.0
  image_picker: ^1.1.1
  google_fonts: ^6.3.3
  http: ^1.6.0
  go_router: ^14.1.4
  firebase_ai: ^2.3.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  fl_chart: 0.62.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.10
  freezed: ^2.5.2
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
