name: in_the_hood
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^3.5.0
  google_mobile_ads: ^4.0.0
  provider: ^7.0.0
  geolocator: ^10.0.0
  google_fonts: ^6.2.1
  image_picker: ^1.1.1
  cupertino_icons: ^1.0.6
  amplify_flutter: ^1.5.0
  amplify_auth_cognito: ^1.5.0
  amplify_api: ^1.5.0
  amplify_datastore: ^1.5.0
  amplify_storage_s3: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
